spring:
  application:
  name: restful-web-services

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    defer-datasource-initialization: true
    show-sql: true

  security:
    user:
      name: username
      password: password